swagger: '2.0'
info:
  title: Example API
  version: 1.0.0
  description: An example API with a single endpoint


/api/v1/report/drivers:
    get:
      summary: Get a list of all drivers
      responses:
        200:
          description: Sorted list of all drivers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Driver'

components:
  schemas:
    Driver:
      type: object
      properties:
        driver_id:
          type: string
        driver_info:
          type: string
      example:
        driver_id: "1"
        driver_info: "Sebastian Vettel              | FERRARI                       | 1:04.415"
