swagger: '2.0'
info:
  title: Example API
  version: 1.0.0
  description: An example API with a single endpoint


/api/v1/report:
  get:
    summary: List of drivers
    description: Returns a list of all reports
    responses:
      200:
        description: List of all reports
        schema:
          type: array
          items:
            $ref: '#/components/schemas/Driver'

components:
  schemas:
    Driver:
      type: object
      properties:
        id:
          type: string
        driver_info:
          type: string
      example:
        id: "1"
        driver_info: "Sebastian Vettel              | FERRARI                       | 1:04.415"
