swagger: '2.0'
info:
  title: Example API
  version: 1.0.0
  description: An example API with a single endpoint

get:
  summary: List of drivers
  description: Returns a list of all reports
  parameters:
    - name: format
      in: query
      description: The format of the response (json or xml)
      required: false
      type: string
      enum:
        - json
        - xml
  responses:
    200:
      description: List of all reports
      schema:
        type: array
        items:
          $ref: '#/definitions/Driver'

definitions:
  Driver:
    type: object
    properties:
      driver_id:
        type: string
      driver_info:
        type: string
    example:
      id: "SVF"
      driver_info: "Sebastian Vettel              | FERRARI                       | 1:04.415"
